/**
 * lib/mireye/fields.ts
 *
 * Defines the comprehensive list of 113 fields (61 Direct + 52 Indirect)
 * fetched from the Mireye API in a single stage.
 */

export const DIRECT_FIELDS = [
  "elevation",
  "slope_degrees",
  "coast_distance_m",
  "soil_drainage_class",
  "bedrock_depth_cm",
  "nearest_flowline_name",
  "nearest_waterbody_name",
  "within_floodplain_polygon",
  "intersects_wetland",
  "wetland_type",
  "nearest_wetland_distance_m",
  "wetlands_within_100m_count",
  "surface_water_permanence_pct",
  "lcms_class",
  "land_use_class",
  "tree_canopy_pct",
  "ndvi_change_5y",
  "cdl_class",
  "is_cultivated",
  "dominant_crop_5y",
  "primary_building_height_m",
  "primary_building_overture_class",
  "nearest_major_road_name",
  "nearest_major_road_distance_m",
  "nearest_power_plant_distance_m",
  "nearest_transmission_line_distance_m",
  "nearest_gas_pipeline_distance_m",
  "nearest_public_water_system_name",
  "nearest_airport_distance_m",
  "political_county",
  "political_locality",
  "intersects_conservation_easement",
  "intersects_protected_area",
  "protected_area_gap_status",
  "intersects_critical_habitat",
  "critical_habitat_status",
  "parcel_geometry_wkt",
  "parcel_boundary_geojson",
  "parcel_id",
  "parcel_area_m2",
  "parcel_address",
  "parcel_owner",
  "parcel_zoning",
  "seismic_design_category",
  "seismic_pga_2pct_50yr_g",
  "design_wind_speed_mph",
  "wildfire_annual_frequency",
  "tornado_annual_frequency",
  "hail_annual_frequency",
  "lightning_annual_flash_days",
  "landslide_susceptibility_index",
  "nearest_hazardous_facility_distance_m",
  "nearest_groundwater_well_depth_to_water_m",
  "fiber_provider_count",
  "fiber_broadband_available",
  "mobile_5g_coverage_class",
  "soil_shrink_swell_class",
  "prime_farmland_classification",
  "in_air_quality_nonattainment",
  "nearest_brownfield_distance_m",
  "nearest_superfund_distance_m",
] as const;

export const INDIRECT_FIELDS = [
  "aspect_degrees",
  "aspect_cardinal",
  "soil_map_unit_name",
  "intersects_nhd_area",
  "huc_12_name",
  "wetland_subtype",
  "wetland_acres",
  "wetlands_within_500m_count",
  "ndvi_current",
  "primary_building_num_floors",
  "primary_building_footprint_sqm",
  "nearest_power_plant_name",
  "nearest_power_plant_primary_fuel",
  "nearest_transmission_line_voltage_kv",
  "nearest_transmission_line_voltage_class",
  "nearest_transmission_line_status",
  "max_transmission_line_voltage_kv_within_radius",
  "max_transmission_line_voltage_class_within_radius",
  "nearest_rail_line_distance_m",
  "nearest_airport_name",
  "political_region",
  "easement_holder",
  "easement_type",
  "easement_purpose",
  "easement_acres",
  "easement_year_established",
  "protected_area_name",
  "protected_area_designation",
  "protected_area_manager",
  "protected_area_public_access",
  "critical_habitat_species",
  "critical_habitat_listing_status",
  "parcel_apn",
  "mean_annual_dry_bulb_temperature_degc",
  "mean_annual_relative_humidity_pct",
  "days_above_32c_annual_count",
  "mean_annual_snow_cover_days",
  "nearest_dam_distance_m",
  "nearest_dam_hazard_potential",
  "high_hazard_dams_within_10km",
  "nearest_hazardous_facility_name",
  "electric_utility_service_territory",
  "public_water_system_population_served",
  "nearest_urban_area_distance_m",
  "in_shale_play",
  "nearest_shale_play_name",
  "drought_category",
  "air_quality_nonattainment_pollutants",
  "air_quality_worst_classification",
  "brownfields_within_radius_count",
  "superfund_sites_within_radius_count",
  "nearest_gas_pipeline_type",
] as const;

export const ALL_RELEVANT_FIELDS = [...DIRECT_FIELDS, ...INDIRECT_FIELDS] as const;

export type FullAssessmentResult = Record<string, unknown>;
